controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app.swagger:
    path: /notifications/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /notifications/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

