name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

    steps:
    - name: Получение кода
      uses: actions/checkout@v2

    - name: Настройка PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Установка зависимостей Composer
      run: |
        cd docker &&
        docker-compose exec ms_notification composer install

    - name: Создание базы данных (если еще не существует)
      run: |
        cd docker &&
        docker-compose exec ms_notification php bin/console doctrine:database:create --if-not-exists

    - name: Выполнение миграций
      run: |
        cd docker &&
        docker-compose exec ms_notification php bin/console doctrine:migrations:migrate --no-interaction
