name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display current directory
      run: pwd

    - name: List files in the directory
      run: ls -al

    - name: Run make up
      run: make up

    - name: Display Docker containers
      run: docker ps
